/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Categoria;

/**
 *
 * @author cesar
 */
public class PanelRegistrarCategoria extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarCategoria
     */
    public PanelRegistrarCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(534, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Titulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Titulo.setText("Panel para REGISTRAR CATEGORIAS");
        add(Label_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 24, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Titulo;
    // End of variables declaration//GEN-END:variables
}
