/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Ventas.PanelConsultarVentas;

/**
 *
 * @author cesar
 */
public class PanelVentas extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentas
     */
    
    PanelConsultarVentas consulta; 
    public PanelVentas() {
        initComponents();
        
        //Propiedades de la mini-panel de CONSULTAR VENTAS.
        consulta = new PanelConsultarVentas();
        consulta.setBounds(0,0,356, 392);
        PanelVariableVenta.add(consulta);
        consulta.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelVariableVenta = new javax.swing.JPanel();
        Btn_AnularVenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(952, 608));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Panel VENTAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, -1, -1));

        PanelVariableVenta.setBackground(new java.awt.Color(255, 255, 255));
        PanelVariableVenta.setPreferredSize(new java.awt.Dimension(356, 392));
        PanelVariableVenta.setLayout(null);
        add(PanelVariableVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 16, -1, -1));

        Btn_AnularVenta.setText("ANULAR VENTA");
        Btn_AnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AnularVentaActionPerformed(evt);
            }
        });
        add(Btn_AnularVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        jButton1.setText("jButton1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AnularVentaActionPerformed
        consulta.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_Btn_AnularVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AnularVenta;
    private javax.swing.JPanel PanelVariableVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
