/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.Almacen.PanelAnadirProducto;
import Vista.Almacen.PanelCategorias;
import Vista.Almacen.PanelVerProductos;

/**
 *
 * @author cesar
 */
public class PanelAlmacen extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlmacen
     */
    PanelAnadirProducto anadir;
    PanelCategorias categorias;
    PanelVerProductos productos; 
    public PanelAlmacen() {
        initComponents();
        
        //Propiedades de panel AÑADIR
        anadir= new PanelAnadirProducto(this);
        anadir.setBounds(0, 0, 920, 576);
        PanelDinamicoAlmacen.add(anadir);
        anadir.setVisible(false);
        
        //Propiedades del panel CATEGORIAS
        categorias= new PanelCategorias(this);
        categorias.setBounds(0, 0, 920, 576);
        PanelDinamicoAlmacen.add(categorias);
        categorias.setVisible(false); 
        
        //Propiedades del panel VER PRODUCTOS. 
        productos= new PanelVerProductos(this);
        productos.setBounds(0, 0, 920, 576);
        PanelDinamicoAlmacen.add(productos);
        productos.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDinamicoAlmacen = new javax.swing.JPanel();
        Btn_Anadir = new javax.swing.JButton();
        Btn_VerProductos = new javax.swing.JButton();
        Btn_Categorias = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(952, 608));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDinamicoAlmacen.setPreferredSize(new java.awt.Dimension(920, 576));

        Btn_Anadir.setText("AÑADIR PRODUCTO");
        Btn_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AnadirActionPerformed(evt);
            }
        });

        Btn_VerProductos.setText("VER PRODUCTOS");
        Btn_VerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerProductosActionPerformed(evt);
            }
        });

        Btn_Categorias.setText("CATEGORIAS");
        Btn_Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CategoriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDinamicoAlmacenLayout = new javax.swing.GroupLayout(PanelDinamicoAlmacen);
        PanelDinamicoAlmacen.setLayout(PanelDinamicoAlmacenLayout);
        PanelDinamicoAlmacenLayout.setHorizontalGroup(
            PanelDinamicoAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDinamicoAlmacenLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(Btn_VerProductos)
                .addGap(141, 141, 141)
                .addComponent(Btn_Anadir)
                .addGap(150, 150, 150)
                .addComponent(Btn_Categorias)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        PanelDinamicoAlmacenLayout.setVerticalGroup(
            PanelDinamicoAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDinamicoAlmacenLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(PanelDinamicoAlmacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Anadir)
                    .addComponent(Btn_VerProductos)
                    .addComponent(Btn_Categorias))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        add(PanelDinamicoAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //Metodo que visualiza el tablero de almacen.
    public void PrimeraVistaAlmacen(){
        Btn_Anadir.setVisible(true);
        Btn_Categorias.setVisible(true);
        Btn_VerProductos.setVisible(true);
        anadir.setVisible(false);
        categorias.setVisible(false);
        productos.setVisible(false);
        revalidate();
        repaint();
        
    }
    
    private void Btn_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AnadirActionPerformed
        // TODO add your handling code here:
        //setSize(920,576);
        Btn_Anadir.setVisible(false);
        Btn_Categorias.setVisible(false);
        Btn_VerProductos.setVisible(false);
        anadir.setVisible(true);
        categorias.setVisible(false);
        productos.setVisible(false);
        
        revalidate();
        repaint();
                
        
    }//GEN-LAST:event_Btn_AnadirActionPerformed

    private void Btn_VerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerProductosActionPerformed
        // Imprimir panel de Ver Productos
         Btn_Anadir.setVisible(false);
        Btn_Categorias.setVisible(false);
        Btn_VerProductos.setVisible(false);
        anadir.setVisible(false);
        categorias.setVisible(false);
        productos.setVisible(true);
        
        revalidate();
        repaint();
                
    }//GEN-LAST:event_Btn_VerProductosActionPerformed

    private void Btn_CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CategoriasActionPerformed
        // Imprimir panel de categorias
         Btn_Anadir.setVisible(false);
        Btn_Categorias.setVisible(false);
        Btn_VerProductos.setVisible(false);
        anadir.setVisible(false);
        categorias.setVisible(true);
        productos.setVisible(false);
        
        revalidate();
        repaint();
                
    }//GEN-LAST:event_Btn_CategoriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Anadir;
    private javax.swing.JButton Btn_Categorias;
    private javax.swing.JButton Btn_VerProductos;
    private javax.swing.JPanel PanelDinamicoAlmacen;
    // End of variables declaration//GEN-END:variables
}
