/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author cesar
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    //Declarar los paneles existentes
    PanelDevoluciones devoluciones;
    PanelVentas ventas;
    PanelAlmacen almacen;
    PanelReportes reportes;
    PanelCaja caja;
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        PanelVariable.setBounds(216, 88, 952, 608);
        //Instancias paneles e inicializar sus propiedades.
        //Propiedades panel DEVOLUCIONES.
        devoluciones = new PanelDevoluciones();
        devoluciones.setBounds(0, 0, 952, 608);
        PanelVariable.add(devoluciones);
        devoluciones.setVisible(false);
        
        //Propiedades panel VENTAS. 
        ventas = new PanelVentas();
        ventas.setBounds(0, 0, 952, 608);
        PanelVariable.add(ventas);
        ventas.setVisible(false);
        
        //Propiedades de ALMACEN
        almacen= new PanelAlmacen();
        almacen.setBounds(0, 0, 952, 608);
        PanelVariable.add(almacen);
        almacen.setVisible(false);
        
        //Propiedades de REPORTES
        reportes= new PanelReportes();
        reportes.setBounds(0, 0, 952, 608);
        PanelVariable.add(reportes);
        reportes.setVisible(false);
        
        //Propiedades de CAJA
        caja= new PanelCaja();
        caja.setBounds(0, 0, 952, 608);
        PanelVariable.add(caja);
        caja.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVentana = new javax.swing.JPanel();
        Cerrar = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        LabelFecha = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        LabelCerrarSesion = new javax.swing.JLabel();
        PanelBarraMenu = new javax.swing.JPanel();
        Btn_Devoluciones = new javax.swing.JButton();
        Btn_Ventas = new javax.swing.JButton();
        Btn_Almacen = new javax.swing.JButton();
        Btn_Reporte = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Btn_Tablero = new javax.swing.JButton();
        PanelVariable = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelVentana.setBackground(new java.awt.Color(15, 149, 245));
        PanelVentana.setPreferredSize(new java.awt.Dimension(1168, 32));

        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVentanaLayout = new javax.swing.GroupLayout(PanelVentana);
        PanelVentana.setLayout(PanelVentanaLayout);
        PanelVentanaLayout.setHorizontalGroup(
            PanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVentanaLayout.createSequentialGroup()
                .addGap(1061, 1061, 1061)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelVentanaLayout.setVerticalGroup(
            PanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVentanaLayout.createSequentialGroup()
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(PanelVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Header.setBackground(new java.awt.Color(196, 196, 196));
        Header.setPreferredSize(new java.awt.Dimension(1168, 56));

        Titulo.setBackground(new java.awt.Color(51, 0, 51));
        Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Yoyis Papelería");

        LabelFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelFecha.setForeground(new java.awt.Color(0, 0, 0));
        LabelFecha.setText("Fecha y hora");

        LabelUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setText("Usuario");

        LabelCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabelCerrarSesion.setForeground(new java.awt.Color(0, 0, 0));
        LabelCerrarSesion.setText("Cerrar Sesión");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(LabelFecha)
                .addGap(275, 275, 275)
                .addComponent(LabelUsuario)
                .addGap(101, 101, 101)
                .addComponent(LabelCerrarSesion)
                .addGap(15, 15, 15))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo)
                    .addComponent(LabelFecha)
                    .addComponent(LabelUsuario)
                    .addComponent(LabelCerrarSesion))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, -1, -1));

        PanelBarraMenu.setBackground(new java.awt.Color(196, 196, 196));
        PanelBarraMenu.setPreferredSize(new java.awt.Dimension(216, 608));
        PanelBarraMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Devoluciones.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btn_Devoluciones.setText("DEVOLUCIONES");
        Btn_Devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DevolucionesActionPerformed(evt);
            }
        });
        PanelBarraMenu.add(Btn_Devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        Btn_Ventas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btn_Ventas.setText("VENTAS");
        Btn_Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VentasActionPerformed(evt);
            }
        });
        PanelBarraMenu.add(Btn_Ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        Btn_Almacen.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btn_Almacen.setText("ALMACEN");
        Btn_Almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AlmacenActionPerformed(evt);
            }
        });
        PanelBarraMenu.add(Btn_Almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        Btn_Reporte.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btn_Reporte.setText("REPORTE");
        Btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReporteActionPerformed(evt);
            }
        });
        PanelBarraMenu.add(Btn_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("CAJA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelBarraMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        Btn_Tablero.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Btn_Tablero.setText("TABLERO");
        PanelBarraMenu.add(Btn_Tablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        getContentPane().add(PanelBarraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, -1, -1));

        PanelVariable.setBackground(new java.awt.Color(102, 51, 255));
        PanelVariable.setPreferredSize(new java.awt.Dimension(952, 608));

        javax.swing.GroupLayout PanelVariableLayout = new javax.swing.GroupLayout(PanelVariable);
        PanelVariable.setLayout(PanelVariableLayout);
        PanelVariableLayout.setHorizontalGroup(
            PanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        PanelVariableLayout.setVerticalGroup(
            PanelVariableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(PanelVariable, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 88, 950, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CerrarActionPerformed

    private void Btn_VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VentasActionPerformed
        //Llamado a impresión del panel VENTAS. 
        
        setSize(1168,696);
        devoluciones.setVisible(false);
        ventas.setVisible(true);
        almacen.setVisible(false);
        reportes.setVisible(false);
        caja.setVisible(false);
        revalidate();
        repaint();
        
    }//GEN-LAST:event_Btn_VentasActionPerformed

    private void Btn_DevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DevolucionesActionPerformed
        // TODO add your handling code here:
         setSize(1168,696);
        devoluciones.setVisible(true);
        ventas.setVisible(false);
        almacen.setVisible(false);
        reportes.setVisible(false);
        caja.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_Btn_DevolucionesActionPerformed

    private void Btn_AlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AlmacenActionPerformed
        // Lamado a impresion del panel ALMACEN
        setSize(1168,696);
        devoluciones.setVisible(false);
        ventas.setVisible(false);
        almacen.PrimeraVistaAlmacen();
        almacen.setVisible(true);
        reportes.setVisible(false);
        caja.setVisible(false);
        revalidate();
        repaint();
        
    }//GEN-LAST:event_Btn_AlmacenActionPerformed

    private void Btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReporteActionPerformed
        // Impresión del panel REPORTES
        setSize(1168,696);
        devoluciones.setVisible(false);
        ventas.setVisible(false);
        almacen.setVisible(false);
        reportes.setVisible(true);
        caja.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_Btn_ReporteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Impresion del panel CAJA
        setSize(1168,696);
        devoluciones.setVisible(false);
        ventas.setVisible(false);
        almacen.setVisible(false);
        reportes.setVisible(false);
        caja.setVisible(true);
        revalidate();
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Almacen;
    private javax.swing.JButton Btn_Devoluciones;
    private javax.swing.JButton Btn_Reporte;
    private javax.swing.JButton Btn_Tablero;
    private javax.swing.JButton Btn_Ventas;
    private javax.swing.JButton Cerrar;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LabelCerrarSesion;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelBarraMenu;
    private javax.swing.JPanel PanelVariable;
    private javax.swing.JPanel PanelVentana;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
