/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Ventas;


import Controlador.ControladorVentas;
import Modelo.Venta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesar
 */
public class PanelConsultarVentas extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsultarVentas
     */
    
    DefaultTableModel modelo;
    ControladorVentas controlador;
    public PanelConsultarVentas() {
        initComponents();
        controlador=new ControladorVentas();
        //Definir la tabla
        modelo = new DefaultTableModel();
        String[] columnas = {"Folio", "Fecha", "Total"};
        modelo.setColumnIdentifiers(columnas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Btn_VerTodo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(356, 392));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "folio venta", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, 110));

        Btn_VerTodo.setText("Ver todo");
        Btn_VerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerTodoActionPerformed(evt);
            }
        });
        add(Btn_VerTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_VerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerTodoActionPerformed
        // Realizar una consulta de todas la ventas e imprimir en tabla
        ArrayList<Venta> listaVentas;
        //Mandar a llamar al metodo de la clase controlador que realiza la consulta
        listaVentas=controlador.consultarTodas();
         
        //Imprimir en tabla. 
        modelo.setRowCount(0);
        Object[] datosFila = new Object[3]; //El tamaño de la lista es igual al numero de columnas (3)
        //Recorrer lista de resultados objenidos de la consulta y agregarlo a la lista de filas de la tabla
        for(Venta v : listaVentas){
            datosFila[0]= v.getFolio_venta();
            datosFila[1]= v.getFecha();
            datosFila[2]= v.getTotal();
            modelo.addRow(datosFila);
        }
        //Se dibuja el modelo en la tabla
        Tabla.setModel(modelo);
        
    }//GEN-LAST:event_Btn_VerTodoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_VerTodo;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
